name: Firebase Functions — CI & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: firebase-functions-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          # Use ci when the lockfile matches; fall back to install on first pass
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      # Google Cloud auth using a service account JSON stored as a repo secret
      # Create this once:
      #   Repo → Settings → Secrets and variables → Actions → New secret
      #   Name: FIREBASE_SERVICE_ACCOUNT, Value: <the JSON content>
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Show Firebase CLI version
        run: firebase --version

      # Deploy only Cloud Functions (uses firebase.json + .firebaserc)
      # We also pass OPENAI_API_KEY to keep the analyzer happy in CI
      - name: Deploy Functions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: firebase deploy --only functions --non-interactive
